### PR TITLE
Fix for #778 when your logged in as admin

### PR DESCRIPTION
**Pull request by equivalentideas**
This adds absolute path references for partials in the applications/show view, which fixes a bug where you get a template not found error if your comment gets rejected and the show view loads from the comments controllers. See #778 for more details on the bug.

e79f79f was a fix for this, but it didn't work for admins because their are other partials that only they see that were not included.

This also moves the comment form related partials to a more logical home in the comments view folder.

### CODE REVIEW

**Comment by equivalentideas** [comment]
Assigning to @henare for review/merge

**Comment by henare** [comment]
Thanks for remembering this :alien: 

There are now two `councillor_message_form` partials, is this correct?

**Comment by equivalentideas** [comment]
> There are now two councillor_message_form partials, is this correct?

Nope :S Sorry I missed that.

**Comment by equivalentideas** [comment]
> There are now two councillor_message_form partials

I've removed the stay file in defa00f. Thanks for picking that up @henare , assigning back to you.

**Pull request merged**
