### PR TITLE
Added a short instruction of how to contribute 

### LINKED ISSUE #1234: Create easy and lightweight instruction for contribution
We created a step-by-step instruction of the councillor contribution with a non-technical user in mind in the issue #1216.
However, after user tests, it became apparent that the instruction needs to be shorter, spontaneous, and minimal to be useful.  

See  https://github.com/openaustralia/planningalerts/pull/1216#issuecomment-323896229

### PR DESCRIPTION
**Pull request by hisayohorie**
This is to fix #1234 

I added a brief instruction of the contribution on the same page as the form to be spontaneous.
It looks like this
screen shot 2017-08-22 at 4 16 26 pm

Please let me know what you think @equivalentideas @henare 🎸

### CODE REVIEW

**Comment by equivalentideas** [comment]
I think this is a better place to start from, I showed it to volunteer Pip and she thought that was a really good :)

I just had a bit of a play with this locally, to see if I could work out a way to make it not take up as much of the page. Also, once the person knows what to do, these instructions take up a lot of space.

Here's what I came up with, using the <details> element to make the text available on request:

On load:
screen shot 2017-08-23 at 4 42 45 pm

After hitting 'show instructions':
screen shot 2017-08-23 at 4 43 08 pm

I also tried to make the page heading friendlier (and also to make it clearer you can submit lots of councillors together https://github.com/openaustralia/planningalerts/issues/1222 ) and added a sentence reminding people why they should help us :)

What do you recon? I can push those commits up if you think its useful.

**Comment by hisayohorie** [comment]
@equivalentideas I think the `show instruction` is super useful! please push the commit 🎸

**Comment by equivalentideas** [comment]
@hisayohorie sounds good, I'll merged this 👍 Nice work.

**Comment by equivalentideas** [comment]
Deployed! 🚢

**Comment by equivalentideas** [comment]
@hisayohorie in the spirit of [our principle "Share ownership"](https://github.com/openaustralia/australian_local_councillors_popolo/#design-principles), I added a link for people to improve the instructions in https://github.com/openaustralia/planningalerts/commit/cab34e688c7f13e4e4c5af32d5ec88c05346049a

screen shot 2017-08-24 at 6 12 18 pm

I also change it to a markdown file, which is a bit easier to edit :)

**Pull request merged**
