### PR TITLE
Fix for Broken Link "Applications Near "

### PR DESCRIPTION
**Pull request by akve17**
The broken link "Applications Near" was not working because the parameter '@address ' was not set. This parameter has been set in the alerts controller file.

### CODE REVIEW

**Comment by akve17** [comment]
It gives an error "secret_key was not set". This error occurs because the morph key is not set.

**Comment by equivalentideas** [comment]
@akve17 Thanks for this contribution and for explaining how the fix works in your PR description 👍.

A good tip is that if you include the text "Fixes #1120" in your PR description, GitHub creates a link back to the issue and will close it automagically when this is merged.

I'm going to close this PR however because it includes many code changes that are unrelated to the fix and are unexplained. Are they to do with getting your local installation to work?

Could you open I new PR with just the code changes required to fix the issue? I'm happy to help you with the steps to get there if that helps :)

**Comment by akve17** [comment]
@equivalentideas Thanks Luke. I had purposely added those files , so that the new candidates who are working on planning alerts do not face the same issues, but if they are not necessary i will soon make another commit with only the relevant changes.

**Comment by equivalentideas** [comment]
In a Pull Request, it's best to only include the changes that fix the issue you're referring to and exclude all other changes. Submit an individual PR with each change to the application you want to make. If you're making a big change, that changes a lot of code, it's best to explain why each bit is being changed and why it needs to be. Otherwise it's really hard to review the PR. 

>  I had purposely added those files 

There's no way for us to know this, because your PR description says you're just trying to fix the "Applications Near" text. We just have to assume it's a mistake. 

Does that help clear things up? :)

I see you've made [a new PR](https://github.com/openaustralia/planningalerts/pull/1141/files), but it also doesn't explain the purpose of most of the code changes, such as removing the `.env` file.

**Pull request closed without merging**
