### PR TITLE
Allow showing a different price to potential subscribers

### LINKED ISSUE #750: Allow different prices to be shown to different potential subscribers
So we can do cohort testing.

### PR DESCRIPTION
**Pull request by henare**
Resolves #750.

### CODE REVIEW

**Comment by henare** [comment]
Assigning to @equivalentideas for review and merge.

**Comment by equivalentideas** [comment]
Looks great @henare I those couple of questions above.

**Comment by henare** [comment]
@equivalentideas thanks for the review! I'm going to go ahead and merge despite those minor smells because I think we'll smooth them out as we forge ahead.

**Comment by equivalentideas** [comment]
Sounds good :+1:

**Pull request merged**
