### PR TITLE
Set supplied radius or its default to float.

### PR DESCRIPTION
**Pull request by JWells**
This one won't break the or condition so the default will still work.

### CODE REVIEW

**Comment by equivalentideas** [comment]
Thanks @JWells . I think this needs some controller tests for the radius functionality. Would you be up for including these in this PR?

**Comment by JWells** [comment]
No problems, I've added some tests just on the radius variable to keep this PR small.

**Comment by equivalentideas** [comment]
Thanks @JWells . This combined with the new integration tests makes me feel a little safer :)

**Comment by equivalentideas** [comment]
That’s deployed @JWells thanks again :stars:

**Pull request merged**
