### PR TITLE
Fix Google Maps sensor warning

### PR DESCRIPTION
**Pull request by CloCkWeRX**
https://www.planningalerts.org.au/applications/774752

Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required

### CODE REVIEW

**Comment by henare** [comment]
Hey @CloCkWeRX thank you for this! :sparkles: 

It's best if PRs are merged and then deployed immediately afterwards. This means that master and what's deployed is always as close together as possible. This also means that if other things are merged into master in the mean time and you deploy and see problems, you're not confused about the source of those problems.

I've assigned this PR to me to deploy now :rocket: 

For future PRs we either need to get you deploying or you'll need to assign it to someone to review and deploy. How does that sound?

**Comment by henare** [comment]
I just ran `bundle exec cap --set-before stage=production deploy:pending` to check that I'm only deploying these commits :+1:

**Comment by henare** [comment]
Deployed and confirmed we're not seeing the warning anymore.

**Comment by CloCkWeRX** [comment]
> assign it to someone to review and deploy.
I prefer that, I can explode less things that way :)

**Pull request merged**
