### PR TITLE
Add banner to alerts for people with a trial subscription

### LINKED ISSUE #695: Alerts for people on a trial subscription should include a banner
That tells them about the trial and about how they can sign up.

### PR DESCRIPTION
**Pull request by henare**
Closes #695.

### CODE REVIEW

**Comment by henare** [comment]
Functionally this is ready to go. Since no one has subscriptions (trial or otherwise) it should be safe to merge and deploy.

@equivalentideas let me know when you're happy with the language and other design elements and we can merge and deploy this :sheep:

**Comment by equivalentideas** [comment]
Awesome thanks!

**Comment by equivalentideas** [comment]
I'm happy with where it’s at. Here's what it looks like:

screen shot 2015-08-13 at 3 05 07 pm
screen shot 2015-08-13 at 3 05 19 pm

**Comment by henare** [comment]
>Trial subscription 13 days left

...sounds robotic to me :fax:

**Comment by equivalentideas** [comment]
How do you feel about:

> You have 13 trial days left

Sounds like are you'd tell someone, but does it sound like trial as in, “you're off to the slammer mate” (or, am I the only one who thinks of that?)

**Comment by henare** [comment]
Yeah I think you're right, it joins "trial" and "days" too much.

This is simple and clear:

>Your trial subscription has 7 days remaining

**Comment by equivalentideas** [comment]
Nice. I'll just adjust the css to make it fit small screens.

**Comment by equivalentideas** [comment]
I've made those adjustments. Assigning back to you.

screen shot 2015-08-13 at 4 48 30 pm
screen shot 2015-08-13 at 4 36 26 pm

**Comment by henare** [comment]
>Assigning back to you.
>...
>This branch has conflicts that must be resolved

Aww.

**Comment by equivalentideas** [comment]
:(

**Pull request merged**
