### PR TITLE
Add basic styles to the councillor contribution form

### PR DESCRIPTION
**Pull request by equivalentideas**
This PR closes https://github.com/openaustralia/planningalerts/issues/1180 by adding some basic styles to get the councillor contribution form to a first pass we can present to people.

The changes are:

* Get the heading down to a size that doesn't dominate the form.
* Style the form input elements to match the general app style that works well, bolder labels and clearer inputs.
* Differentiate the submit form and add a councillor buttons, in both colour and proximity.
* Align the form inputs, and the submitted council records horizontally, so that the names and emails of all the councillors submitted line up. This helps you see if there's a typo in the email formatting, and quickly scan up and down the names.
* [Remove the 'councillors submitted' heading](https://github.com/openaustralia/planningalerts/commit/3e7e125febcc268d0584748099fa9a4a080129c1) and the [add a councillor](https://github.com/openaustralia/planningalerts/commit/ed9c1120fe921df90ce9b3c947b08905949cb195) heading. I think these are both unnecessary (see commit messages for more).
* Bring more focus to the data being inputted by [making the text bigger](https://github.com/openaustralia/planningalerts/commit/54d82577a32b2f47d102bd6ff61dcc1d4e15bb32) and [fading back the labels a little](https://github.com/openaustralia/planningalerts/commit/0c9d3af35b991f00a9c4fa4aa9c1d214ef6b1f15).

## Before

screen shot 2017-08-01 at 1 35 34 pm

## After

screen shot 2017-08-01 at 1 35 04 pm

### CODE REVIEW

**Comment by equivalentideas** [comment]
@hisayohorie I just need to do a little bit of testing across browsers then I'll assign you to review this :)

**Comment by equivalentideas** [comment]
@hisayohorie I just fixed a bug in the layout for Chrome and Safari.

Could you please review this code and the appearance? Let me know if you have any questions or think we should make some changes 👍

**Comment by hisayohorie** [comment]
@equivalentideas looks good to me 🚀 👍

**Comment by equivalentideas** [comment]
@hisayohorie Great, thanks for that. I'll merge this.

**Pull request merged**
