### PR TITLE
#442 Add home_page attribute for authorities

### LINKED ISSUE #442: Add link to home page of planning authority website on authority detail page (PA-429)
<p>This came out of discussions with John from homesales.com.au</p>

* [x] Add a field in the database (done in https://github.com/openaustralia/planningalerts/pull/1242#issuecomment-327049719 by @hisayohorie 🍁 )
* [x] Fill in the values (we've already collected a lot of them, see https://github.com/openaustralia/planningalerts/issues/1244 )
* [ ] Show the values on the authority detail page
* [ ] Deliver this in the api

---

**Issue details imported from Jira:**

| Detail | Value |
| --- | --- |
| Assignee | Unassigned |
| Reporter | Matthew Landauer |
| Created | 2012-09-18 17:36:46 |
| Updated | 2012-09-18 17:36:46 |

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Cleaner version of #940.

Closes #442.
## TODO
- [x] Add a field in the database
- [ ] Fill in the values
- [x] Show the values on the authority detail page
- [ ] Deliver this in the api

### CODE REVIEW

**Comment by henare** [comment]
I'll need to have a think about this. I'm hesitant to merge when we don't have any immediate plans to use this.

**Comment by CloCkWeRX** [comment]
k; for the overall viability of it make sure we clobber #442 if its not useful :)

**Comment by henare** [comment]
I now notice that on #442 there is a list of things that need to be done. For this to be complete they all need to be done, then this is a definite :+1: for merge.

@CloCkWeRX I've added that list to the description and I'll assign it back to you. Can you please also add a screenshot of what this looks like on the authority page so that can be reviewed too?

**Comment by CloCkWeRX** [comment]
I'll address the data collection separately (source 1: we have a spreadsheet or source 2: Probably can infer the majority of the homepages from authority.email.split("@").last; but didn't want to stick that in a migration.).

Will go look at the API stuff.

**Comment by equivalentideas** [comment]
I'm going to close this as it's over a year without movement. Please feel welcome to re-open if need be :)

**Comment by equivalentideas** [comment]
This has been done is https://github.com/openaustralia/planningalerts/pull/1242#issuecomment-327049719 🎉 

The next step is to extract the data we've already collected and add it where we can https://github.com/openaustralia/planningalerts/issues/1244

**Pull request closed without merging**
