### PR TITLE
Upgrade to Rails 4.2.7

### PR DESCRIPTION
**Pull request by equivalentideas**
Todo:

* [x] remove 'foreigner' gem, as [foreign keys are now supported by Rails](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#foreign-key-support).
* [x] resolve notice "Requiring `rspec/autorun` when running RSpec via the `rspec` command is deprecated. Called from /Users/Luke/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:274:in `require'."
* [x] resolve test failure in rspec ./spec/mailers/comment_notifier_spec.rb:105 # CommentNotifier#send_comment_via_writeit! sends the comment to the WriteIt API, and stores the created WriteIt message’s id on the comment
* [x] play around on staging.

@henare I’m struggling with that test failure in send_comment_via_writeit . Would be good to look at this together.

### CODE REVIEW

**Comment by equivalentideas** [comment]
> DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.
> 
> You can opt into the new behavior and remove this warning by setting:
> 
>   config.active_record.raise_in_transactional_callbacks = true
> 
>  (called from block in tsort_each at /Users/Luke/.rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/tsort.rb:150)

One of our gems is raising this deprecation warning. Turning this new behaviour on doesn't results in any more test failures. It feels right to me to turn this on and if we come across errors because it, deal with them. On the other hand, if we leave this as is, things will keep working as they do and we'll hit those problems when we go to rails 5 in the future (if there are any).

**Comment by henare** [comment]
>@henare I’m struggling with that test failure in send_comment_via_writeit . Would be good to look at this together.

@equivalentideas I think it's happening because of the [changes to Action Mailer](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#action-mailer):

>Previously, calling a mailer method on a mailer class will result in the corresponding instance method being executed directly. With the introduction of Active Job and #deliver_later, this is no longer true.

**Comment by equivalentideas** [comment]
Legend @davwood has resolved that test failure for us. I'm going to test out a few basic things in development and then this should be good to deploy to staging.

* [ ] test rebuilding the database
* [ ] test sending alert mail
* [ ] test scraping

**Comment by equivalentideas** [comment]
>  test rebuilding the database

Getting a failure running `bundle exec rake db:setup` when it gets to `seed`:

```
** Invoke db:structure:load_if_sql (first_time)
** Invoke db:create
** Invoke environment
** Execute db:structure:load_if_sql
** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment
** Execute db:abort_if_pending_migrations
rake aborted!
Errno::ECONNREFUSED: Connection refused - connect(2)
```

I think this is related to ActionMailer, but gonna have lunch first :)

**Comment by equivalentideas** [comment]
> I think this is related to ActionMailer, but gonna have lunch first :)

This passes if I have foreman running in the background. Strange. It's building fine on CI so I'm gonna leave this.

**Comment by equivalentideas** [comment]
I've tested running scrape and that alert emails are sent locally. Deploying to staging now.

**Comment by equivalentideas** [comment]
This looks all good to me, I've clicked around on staging. Signed up for an alerts and set scrapers running successfully.

**Comment by equivalentideas** [comment]
Thanks to @davwood for a great contribution on this. I'ma :shipit:

**Pull request merged**
