### PR TITLE
Fix misc security problems

### PR DESCRIPTION
**Pull request by CloCkWeRX**
There were a number of stale gems with known issues.

Now:
```
$ bundle-audit
No vulnerabilities found
```

### CODE REVIEW

**Comment by henare** [comment]
Superb, thanks @CloCkWeRX! :balloon: 

I've loaded this up locally and made sure everything still looks OK. I specifically checked activeadmin to make sure the Devise update didn't break it and also checked scraping to ensure the Nokogiri update didn't break that.

**Comment by henare** [comment]
This changed introduced a bunch of deprecation warnings. You can see it when you run rake, for example:

```
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
```

**Comment by CloCkWeRX** [comment]
https://github.com/rspec/rspec-core/issues/2210 - can go bump the specs using something like transpec and upgrade to rspec 3 in a bit; but wanted to wait until the majority of stuff is merged/things are settled.

**Comment by henare** [comment]
:+1: worth opening an issue for?

**Pull request merged**
