### PR TITLE
Council directory w controller

### PR DESCRIPTION
**Pull request by hisayohorie**
This is part of the #1182 

To scrape the website_url, we need to change the name of the column in <a href ="https://docs.google.com/spreadsheets/d/1_Ea99E5yXnHXW62o_lRo9khdbccEWfttpy2tyuYZYOE/edit"> the Australian local councillor popolo spreadsheet</a> `council_wesite` to `website` so the `csv_to_popolo` gem can convert the data to json format.

This is still pretty basic, and some polishing can happen in 2nd iteration.

### CODE REVIEW

**Comment by equivalentideas** [comment]
Thanks @hisayohorie does this really need to be on top of the https://github.com/openaustralia/planningalerts/pull/1192#pullrequestreview-52572621 PR commits? It makes this diff much bigger (harder to review). This does seem like a separate concept that should have it's own separate PR.

Unless those commits are necessary, could you move the new commits onto a new branch off the clean `openaustralia:person_contributes_councillor_info`? You can start a new branch and then use `git cherry-pick` to grab the commits you want.

**Comment by hisayohorie** [comment]
@equivalentideas I've been looking into the cherry-pick, and I don't think it is feasible to start from `openaustralia:person_contributes_councillor_info` branch, because of the councillor_contribution model and controller doesn't exist in that branch, and that's where I added the tutorial action. Would it be possible to focus on merging the `multiple_contribution` branch, then come back to this branch, so it will make the diff smaller?

**Comment by equivalentideas** [comment]
Sorry I accidentally closed this when I deleted the old `person_contributes_councillor_info` branch. Changed the base branch to `master` and reopening.

**Comment by equivalentideas** [comment]
Closing this cause I'm pretty sure it's superseded by https://github.com/openaustralia/planningalerts/pull/1242

**Pull request closed without merging**
