### PR TITLE
Explain how the WriteToCouncillors feature works and how to configure/use it in the README

### LINKED ISSUE #957: Document how write to councillors works
In the readme for people working on the project.

### PR DESCRIPTION
**Pull request by equivalentideas**
This adds instructions for configuring and using the WriteToCouncillors feature to the README.

TODOS:

* [x] complete todos in the file
* [x] Explain how to update the councillor data in WriteIt
* [x] try and cut down the text, it's quite long
* [x] add helpful links
* <del>screenshots/gifs?</del> I think this would be too much detail for now

Close #957

### CODE REVIEW

**Comment by equivalentideas** [comment]
I've done a pretty solid draft of this, but I'm gonna set it aside now for the rest of the week.

Next step is resolving a couple more TODOs in there.

**Comment by equivalentideas** [comment]
Assigning to @henare for review. Have I missed any important details?

I've been following this to load councillors and update the data this week and the instructions work pretty well.

**Comment by henare** [comment]
>Assigning to @henare for review. Have I missed any important details?

This is a very thorough and detailed explanation of how everything works under the hood.

**Comment by equivalentideas** [comment]
> This is a very thorough and detailed explanation of how everything works under the hood.

Thanks for that @henare .

**Pull request merged**
