### PR TITLE
Implement councillor comments

### PR DESCRIPTION
**Pull request by equivalentideas**
I'm working through enabling comments to be send to councillors. Pushing this up here so I can share my progress.

### CODE REVIEW

**Comment by equivalentideas** [comment]
I'm just doing the dumb thing, working through the tests.

Currently:

* the list of councillors on the page is dynamic
* you can now confirm your comment and it actually gets created
* your comment gets sent to the email of the councillor you’ve selected instead of the authority

TODO:

* [ ] implement the design of councillor comments
* [ ] only show councillors that belong to the authority in the form list
* [ ] don't let people select councillors who don't have emails
* [ ] don't let the form be submitted if person has selected 'one of my councillors' but haven't selected a councillor
* [ ] enable replies from councillors
* [ ] create a special template for the councillor messages, it currently sends them all the stuff for the authority

+ much much more

**Comment by henare** [comment]
We should merge and deploy this as soon as we can. The feature can remain disabled until it's complete (#856).

Before we can we should review the code. We also need to thoroughly test the changes to the alerts too. Anything else that needs doing before we can merge and deploy?

**Comment by equivalentideas** [comment]
> Anything else that needs doing before we can merge and deploy?

Not that I can think of. That sounds good :+1:

**Comment by equivalentideas** [comment]
Ok, this is all ready to go: We've closed all the issues on the MVP milestone.

I'm going to deploy this to test, and ... test it out before deploying shipping this to production tomorrow.

**Pull request merged**
