### PR TITLE
Contribution guide static page

### LINKED ISSUE #1182: Help people collect councillor information by providing them some instructions on where to get it
Collecting councillor information can be tricky if you don't know where to find it.

### PR DESCRIPTION
**Pull request by hisayohorie**
This is to fix #1182 

I tried to `git cherry-pick` from gigantic #1196 and #1197 and decided just rewrite only the needed code and open a new PR.

I created a haml file for step by step guide of how to make councillor contribution, and added a route for councillor_contribution#guide.

Next step for the guide is #1200, to create a search directory for existing authority website_url, which will be a different PR to keep things simple!

### CODE REVIEW

**Comment by equivalentideas** [comment]
@hisayohorie nice work. I'll have a look through this tomorrow 👍

**Comment by hisayohorie** [comment]
I added more detailed instruction on how to input the name of the councillor without titles such as Alderman, Lord Mayer, Dr, etc) in the guide to respond to the issue #1224 .

I think one way to make this particular instruction available on spot when contributors are making their submission, we can create a link to this segment of the instruction in the councillor contribution submission page.  What do you think @henare @equivalentideas ?

**Comment by equivalentideas** [comment]
After seeing volunteer Pip use the form and ask questions, I think this really extensive guide is a bit more that we know people need at this point. In our catchup the other day also we talked about how people need the instructions before they start collecting the information.

@hisayohorie Would a leaner way to approach this be to do something that was just a paragraph or two at the top of the form? I know Pip is familiar with finding council websites, so isn't a great representative of the more fresh potential contributor, but I feel like we'd be better to test out something a bit lighter and then iterate than start with this really comprehensive guide.

What about something like this:

> 
> You should be able to find the information we need from the Yara Ranges Shire Council website. Find their list of elected "councillors" or "aldermen" and for each one add their full name and email and into the form below.
> 
> * **Full Name** should be just their full name without titles, e.g. for "Lord Mayor Alderman Dr Sue Hicks OAM" just enter "Sue Hicks".
> * **Email** should be the email address for contacting that individual councillor.
> 
> Add all the councillors into the form below and then submit them. If you have any questions or can't find all the information you need, please please let us know, we're here to help. Contact us by email to contact@planningalerts.org.au .

With something like this ☝️ we also have a strong prompt to contact us so we can learn about where people are struggling and then iterate the instructions. I think starting small and simple first is a good approach here.

@hisayohorie what do you think?

**Comment by hisayohorie** [comment]
@equivalentideas I think it's a good idea. It might be ok to have this lengthy instruction somewhere in case, but I think how instruction gets useful is somewhere more interactive and spontaneous

**Comment by equivalentideas** [comment]
> It might be ok to have this lengthy instruction somewhere in case, but I think how instruction gets useful is somewhere more interactive and spontaneous

Agreed, this is still a useful comprehensive guide if we think we need that, so let's not delete the branch for now. It's also been useful in helping us work out what we want to do and in going deep into the process 🚀 Should we close this PR and open a new one with some more light weight introduction instructions?

**Comment by hisayohorie** [comment]
Created a new issue #1234. closing.

**Pull request closed without merging**
